name: Test and Deploy

on:
  
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --cov=render

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run render.py
        run: python render.py

      - name: Configurar usuario de Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Confirmar y enviar cambios (sobreescribiendo si es necesario)
        run: |
          git add "public/index.html"
          git commit -m "Actualizacion de la pagina" || echo "Sin cambios para commitear"
          git push || echo "Nada que enviar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  
